"""empty message

Revision ID: a56927540ce6
Revises: 6246b889ce75
Create Date: 2021-06-22 14:19:47.294283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a56927540ce6'
down_revision = '6246b889ce75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('venue_looking', sa.Boolean(), nullable=False))
    op.add_column('Artist', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'description')
    op.drop_column('Artist', 'venue_looking')
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
